
import { Artwork } from '@/types/artwork';
import { Post } from '@/types/post';

export const artworks: Artwork[] = [
    {
        id: '1',
        title: 'Sunset Landscape',
        description: 'A beautiful painting of a sunset over mountains',
        category: 'Personal',
        tags: ['paint', 'landscape'],
        imageUrl: 'https://picsum.photos/600/800?random=1',
        driveId: 'drive1',
        cdnUrl: 'https://picsum.photos/600/800?random=1',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
    },
    {
        id: '2',
        title: 'Abstract Digital Art',
        description: 'Modern digital abstract composition',
        category: 'Personal',
        tags: ['digital', 'abstract'],
        imageUrl: 'https://picsum.photos/400/600?random=2',
        driveId: 'drive2',
        cdnUrl: 'https://picsum.photos/400/600?random=2',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
    },
    {
        id: '3',
        title: 'Portrait Study',
        description: 'Detailed charcoal portrait',
        category: 'Commissioned',
        tags: ['draw', 'portrait'],
        imageUrl: 'https://picsum.photos/500/700?random=3',
        driveId: 'drive3',
        cdnUrl: 'https://picsum.photos/500/700?random=3',
        hasProcess: true,
        visibility: 'published',
        createdAt: new Date('2025-01-03'),
        updatedAt: new Date('2025-01-03'),
    },
    {
        id: '4',
        title: 'Cityscape at Night',
        description: 'Urban scene with neon lights',
        category: 'Concept/Game Art',
        tags: ['digital', 'city'],
        imageUrl: 'https://picsum.photos/700/500?random=4',
        driveId: 'drive4',
        cdnUrl: 'https://picsum.photos/700/500?random=4',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
    },
    {
        id: '5',
        title: 'Floral Still Life',
        description: 'Oil painting of flowers in vase',
        category: 'Personal',
        tags: ['paint', 'still-life'],
        imageUrl: 'https://picsum.photos/450/650?random=5',
        driveId: 'drive5',
        cdnUrl: 'https://picsum.photos/450/650?random=5',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
    },
    {
        id: '6',
        title: 'Geometric Patterns',
        description: 'Vector art with geometric shapes',
        category: 'Concept/Game Art',
        tags: ['digital', 'geometric'],
        imageUrl: 'https://picsum.photos/550/450?random=6',
        driveId: 'drive6',
        cdnUrl: 'https://picsum.photos/550/450?random=6',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
    },
    {
        id: '7',
        title: 'Fantasy Character',
        description: 'Digital illustration of a fantasy character',
        category: 'Concept/Game Art',
        tags: ['digital', 'fantasy'],
        imageUrl: 'https://picsum.photos/480/720?random=7',
        driveId: 'drive7',
        cdnUrl: 'https://picsum.photos/480/720?random=7',
        hasProcess: true,
        visibility: 'published',
        createdAt: new Date('2025-01-07'),
        updatedAt: new Date('2025-01-07'),
    },
    {
        id: '8',
        title: 'Nature Study',
        description: 'Detailed botanical illustration',
        category: 'Personal',
        tags: ['draw', 'nature'],
        imageUrl: 'https://picsum.photos/520/680?random=8',
        driveId: 'drive8',
        cdnUrl: 'https://picsum.photos/520/680?random=8',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-08'),
        updatedAt: new Date('2025-01-08'),
    },
    {
        id: '9',
        title: 'Sci-Fi Concept',
        description: 'Futuristic cityscape concept art',
        category: 'Concept/Game Art',
        tags: ['digital', 'sci-fi'],
        imageUrl: 'https://picsum.photos/650/550?random=9',
        driveId: 'drive9',
        cdnUrl: 'https://picsum.photos/650/550?random=9',
        hasProcess: true,
        visibility: 'published',
        createdAt: new Date('2025-01-09'),
        updatedAt: new Date('2025-01-09'),
    },
    {
        id: '10',
        title: 'Watercolor Portrait',
        description: 'Soft watercolor portrait study',
        category: 'Commissioned',
        tags: ['paint', 'portrait'],
        imageUrl: 'https://picsum.photos/420/580?random=10',
        driveId: 'drive10',
        cdnUrl: 'https://picsum.photos/420/580?random=10',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-10'),
        updatedAt: new Date('2025-01-10'),
    },
    {
        id: '11',
        title: 'Minimalist Design',
        description: 'Clean and simple geometric design',
        category: 'Concept/Game Art',
        tags: ['digital', 'minimalist'],
        imageUrl: 'https://picsum.photos/500/500?random=11',
        driveId: 'drive11',
        cdnUrl: 'https://picsum.photos/500/500?random=11',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-11'),
        updatedAt: new Date('2025-01-11'),
    },
    {
        id: '12',
        title: 'Animal Study',
        description: 'Detailed wildlife illustration',
        category: 'Personal',
        tags: ['draw', 'animals'],
        imageUrl: 'https://picsum.photos/580/420?random=12',
        driveId: 'drive12',
        cdnUrl: 'https://picsum.photos/580/420?random=12',
        hasProcess: false,
        visibility: 'published',
        createdAt: new Date('2025-01-12'),
        updatedAt: new Date('2025-01-12'),
    },
];

export const posts: Post[] = [
    {
        id: '1',
        title: 'Breaking Down My Latest Character Design',
        slug: 'character-design-breakdown',
        content: 'A detailed look at the process behind my recent fantasy character illustration...',
        tags: ['character', 'tutorial', 'digital'],
        publishDate: '2025-01-15',
        status: 'published',
        excerpt: 'A detailed look at the process behind my recent fantasy character illustration...',
        readTime: '5 min read',
    },
    {
        id: '2',
        title: 'Commission Success Story: From Sketch to Client Joy',
        slug: 'commission-success-story',
        content: 'How a simple commission request turned into a beloved piece for a client...',
        tags: ['commission', 'story'],
        publishDate: '2025-01-10',
        status: 'published',
        excerpt: 'How a simple commission request turned into a beloved piece for a client...',
        readTime: '4 min read',
    },
    {
        id: '3',
        title: 'Tools and Techniques for Digital Artists',
        slug: 'digital-artist-tools',
        content: 'My current workflow and favorite tools for creating digital art...',
        tags: ['tools', 'workflow', 'digital'],
        publishDate: '2025-01-05',
        status: 'published',
        excerpt: 'My current workflow and favorite tools for creating digital art...',
        readTime: '6 min read',
    },
];

export const commissions = [
    { id: '1', title: 'Character Portrait', client: 'Anonymous', status: 'Completed' },
    { id: '2', title: 'Book Cover Design', client: 'Author X', status: 'In Progress' },
    { id: '3', title: 'Logo Design', client: 'Startup Y', status: 'Completed' },
];

export const commissionExamples = [
    { id: '1', title: 'Custom Portrait', image: 'https://picsum.photos/400/300?random=20' },
    { id: '2', title: 'Concept Art', image: 'https://picsum.photos/400/300?random=21' },
];

export const staff = [
    { id: '1', name: 'Artist Name', role: 'Lead Artist', image: 'https://picsum.photos/200/200?random=profile' },
    { id: '2', name: 'Assistant A', role: 'Color Specialist', image: 'https://picsum.photos/200/200?random=staff1' },
    { id: '3', name: 'Assistant B', role: 'Technical Support', image: 'https://picsum.photos/200/200?random=staff2' },
];
